# Generated by Django 4.0.6 on 2022-07-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Текст')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='название')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('ranking', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('status', models.TextField(choices=[('new', 'Новая'), ('moderated', 'После модерации')], default='new', verbose_name='Статус')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
                'db_table': 'цитата',
            },
        ),
    ]
